### ISSUE TITLE
关于mdjs的使用

### ISSUE THREAD

**Issue by chengliang-fe** [xuexb/mdjs#5]
我安装下来的目录
![image](https://cloud.githubusercontent.com/assets/2794666/11606847/e8b85ec2-9b6a-11e5-8133-0e95fabe902e.png)

想问下怎么放markdown文件 和启动（没有nodejs方面的基础）

**Comment by xuexb** [comment]
你不用管`mdjs`目录，只需要在你`markdown`文档根目录添加`index.js`，内容如：

``` js
'use strict';

var Mdjs = require('mdjs');

// 实例化
var app = new Mdjs();

// 清空缓存
app.clear_cache();

// 运行跑起来
app.run();
```

再使用`npm install mdjs`安装`mdjs`，并使用`node index.js`启动这个项目～你先试试

**Comment by xuexb** [comment]
参考 [快速使用](http://github.xuexb.com/mdjs/examples/quick.md) 吧！
